# Generated by Django 2.2.1 on 2019-07-16 10:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyagunluk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruyagunluk',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
